#!/usr/bin/env ruby

HOST = "i.ralph.io"

require 'net/http'

# get id
user = IO.popen("whoami", "r+").gets.chomp
program = ARGV[0].to_s
idfile = "/Users/#{user}/Library/Gyazo/id"
old_idfile = File.dirname(program) + "/gyazo.app/Contents/Resources/id"

id = if File.exist?(idfile)
  File.read(idfile).chomp
elsif File.exist?(old_idfile)
  File.read(old_idfile).chomp
end

# capture png file
tmpfile = "/tmp/image_upload#{$$}.png"
imagefile = ARGV[1]

if imagefile && File.exist?(imagefile) then
  system "sips -s format png \"#{imagefile}\" --out \"#{tmpfile}\""
else
  system "screencapture -i \"#{tmpfile}\""
  if File.exist?(tmpfile) then
    system "sips -d profile --deleteColorManagementProperties \"#{tmpfile}\""  
    dpiWidth    = `sips -g dpiWidth "#{tmpfile}" | awk '/:/ {print $2}'`
    dpiHeight   = `sips -g dpiHeight "#{tmpfile}" | awk '/:/ {print $2}'`
    pixelWidth  = `sips -g pixelWidth "#{tmpfile}" | awk '/:/ {print $2}'`
    pixelHeight = `sips -g pixelHeight "#{tmpfile}" | awk '/:/ {print $2}'`
    if (dpiWidth.to_f > 72.0 and dpiHeight.to_f > 72.0) then
        width  =  pixelWidth.to_f * 72.0 / dpiWidth.to_f
        height =  pixelHeight.to_f* 72.0 / dpiHeight.to_f
        system "sips -s dpiWidth 72 -s dpiHeight 72 -z #{height} #{width} \"#{tmpfile}\""
    end
  end
end

exit unless File.exist?(tmpfile)
imagedata = File.read(tmpfile)
File.delete(tmpfile)

# upload
boundary = '----LOLOLOLOLObuttsLOLOLOLOL----'

data = <<EOF
--#{boundary}\r
content-disposition: form-data; name="imagedata"; filename="#{HOST}"\r
\r
#{imagedata}\r
--#{boundary}--\r
EOF

header = {
  'Content-Length' => data.length.to_s,
  'Content-Type' => "multipart/form-data; boundary=#{boundary}",
  'User-Agent' => "ralphholzmann's screen grabs"
}

Net::HTTP.start(HOST,80) { |http|
  res = http.post("/", data, header)
  url = res.response.body
  IO.popen("pbcopy", "r+") { |io|
    io.write url
    io.close
  }
}

